# Generated by Django 4.0.1 on 2022-02-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
